version: "3.5"

networks:
    posmbot:
        external: false

services:
    server:
        build: .
        container_name: posmbot
        networks:
            - posmbot
        volumes:
            - /var/posmbot:/data
        environment:
            - MASTODON_CLIENT_KEY=${MASTODON_CLIENT_KEY}
            - MASTODON_CLIENT_SECRET=${MASTODON_CLIENT_SECRET}
            - MASTODON_ACCESS_TOKEN=${MASTODON_ACCESS_TOKEN}
            - TWITCH_BOT_USERNAME=${TWITCH_BOT_USERNAME}
            - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
            - TWITCH_SECRET=${TWITCH_SECRET}
            - TWITCH_CHANNEL=${TWITCH_CHANNEL}
